import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Open_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
  fallback: ["sans-serif"],
});

const geistMono = geistSans;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className} antialiased`}>
        <p className={`${geistSans.className} antialiased`}>Test Paragraph</p>
        <nav className="flex justify-center align-middle">
          <ul className="flex justify-center align-middle gap-4 ">
            <Link href="/counter">Counter Page</Link>
            <Link href="/colour">Colour Page</Link>
          </ul>
        </nav>
        <main className="max-w-[960px] mx-auto">{children}</main>
      </body>
    </html>
  );
}
